import re
#project title rules
project_name_re =re.compile(r'প্রকল্প\s*শিরোনাম|Project\s*(T|t)itle(s)?|প্রকল্প\s*নাম|Name\s*of\s*the\s*Project')
project_name_garbage_re=re.compile(r'সমজাতী|Same')
dpp_name_re=re.compile(r'উন্নয়ন\s*প্রকল্প\s*প্রস্তাব\s*\(ডিপিপি\)|উন্নয়ন\s*প্রকল্প\s*ছক\s*,\s*প্রস্ত্মাব\s*\(ডিপিপি\)')
estimated_cost_re=re.compile(r'প্রকল্প\s*প্রাক্কলিত\s*ব্য|Estimated\s*(c|C)ost\s*of\s*the\s*((p|P)roject)?|প্রকল্প\s*ব্য')
investment_cost_re=re.compile(r'প্রকল্প\s*প্রাক্কলিত\s*ব্য|প্রাক্কলিত\s*ব্য')
total_re=re.compile(r'মোট|Total|সবের্মাট')
gob_cost_re=re.compile(r'জিও|G(o|O)B|জওি|স্থানী\s*মুদ্|জওিব')
own_fund_re = re.compile(r'DNCC|নিজস্ব\s*অর্থ|Own\s*Fund|নিজস্ব\s*অর্থ|িজস্ব\s*অথর্')
pa_cost_re = re.compile(r'PA|RPA|P.A|P.A.|প্রকল্প\s*সাহায্য')
other_cost_re=re.compile(r'অন্যান্য|(O|o)thers|অন্যান্য')
not_applicable_re=re.compile(r'প্রযোজ্য|-|00.00|০০.০০|প্রযোজ্য\s*নহ')
original_cost_re=re.compile(r'মূল\s*অনুমোদিত\s*ব্য|Original')
revised_cost_re = re.compile(r'সংশোধিত\s*প্রাক্কলিত\s*ব্য|1st\s*Revision')
number_re=re.compile(r'(\d+|(০|১|২|৩|৪|৫|৬|৭|৮|৯)+).(\d+|(০|১|২|৩|৪|৫|৬|৭|৮|৯)+)')
clear_re=re.compile(r'\S+')
# project date "
date_re= re.compile(r'প্রকল্প\s*বাস্তবায়নকাল|প্রকল্প\s*বাস্ত্মবায়ন\s*কাল|প্রকল্প\s*বাসত্মবায়নকাল|প্রকল্প\s*বাস্ত্মবায়ন\s*কাল|প্রকল্প\s*বাস্তবায়ন\s*কাল|প্রকল্প\s*বাস্ত্মবায়নকাল|প্রকল্প\s*বাস্ত্মবায়নকাল|প্রকল্প\s*মেয়াদ|Project\s*(i|I)mplementation\s*(p|P)eriod|প্রকল্প\s*বাস্তবায়ণকাল')
start_date_re = re.compile(r'শুরম্নর\s*তারিখ|শুরুর\s*তারিখ|শুরম্নর\s*তারিখ|আরম্ভ|Date\s*of\s*(c|C)ommencement|Date\s*of\s*the\s*(c|C)ommencement|শুরম্নর\s*কাল|শুরুর\s*কাল')
end_date_re = re.compile(r'সমাপ্তির\s*তারিখ|সমাপ্তি|Date\s*of\s*(c|C)ompletion|সমাপ্তির\s*কাল|সমাপ্তির\s*কাল')
original_date_re = re.compile(r'মূল|Original')
revised_date_re=re.compile(r'সংশোধিত\s*\(১ম\)|Revised\s*\(1st\)')
# responsible organization "
point_re = re.compile(r'(\d|(০|১|২|৩|৪|৫|৬|৭|৮|৯)).(\d|(০|১|২|৩|৪|৫|৬|৭|৮|৯))')
ministy_re = re.compile(r'উদ্যোগী\s*মন্ত্রণাল\s*/\s*বিভাগ|উদ্যোগী\s*মন্ত্রণাল\s*/\s*বিভাগ|উদ্যোগী\s*মন্ত্রণাল|Sponsoring\s*Ministry\s*/\s*Division|উদ্যোগী\s*মন্ত্রনাল|Sponsoring\s*/\s*Ministry\s*/\s*Division|Sponsoring\s*Ministry|উদ্দ্যোগী\s*মন্ত্ম্রণাল|Administrative\s*Ministry\s*/\s*Division')
partner_ministry_re = re.compile(r'Partner\s*Ministry')
agency_re = re.compile(r'বাসত্মবায়নকারী\s*সংস্থা|বাস্তবায়ণকারী\s*সংস্থা|বাস্তবায়নকারী\s*সংস্থা|বাস্ত্মবায়নকারী\s*সংস্থা|Executing\s*Agency|বাস্তাবায়নকারী\s*সংস্থা|Implementation\s*Agency|Implementing\s*Agency|Executing\s*Agency')
partner_agency_re = re.compile(r'Partner\s*Executing\s*Agency')
sector_re = re.compile(r'Concern\s*sector')
planning_re = re.compile(r'(C|c)oncern(ed)?\s*(d|D)ivision\s*of\s*(p|P)lanning\s*(c|C)ommission|পরিকল্পনা\s*কমিশন\s*সংশ্লিষ্ট\s*বিভাগ|পরিকল্পনা\s*কমিশন\s*সংশ্লিষ্ট|সংশিস্নষ্ট\s*বিভাগ|পরিকল্পনা\s*কমিশন\s*সংশ্লিষ্ট\s*বিভাগ|Planning\s*Commission')
trackorg_re = re.compile(r'Objectives\s*of\s*Project|প্রকল্প\s*উদ্দেশ্য\s*লক্ষ্যমাত্|cÖK‡íi\s*D‡Ïk¨|Objectives|প্রকল্প\s*উদ্দেশ্য|প্রকল্প\s*ব্য|(O|o)bjective\s*of\s*the\s*(P|p)roject')
